export enum OptionCode {
  BACK = -100,
  CLOSE,
  TITLE,
  WELCOME = 0,
  MAIN_MENU,
  MAIN_PURCHASE,
  PURCHASE_BACK,
  MAIN_HELP,
  MAIN_NEW_TOKEN,
  MAIN_START_STOP,
  MAIN_SET_TARGET,
  MAIN_SET_RATING,
  MAIN_SET_BUY_AMOUNT,
  MAIN_WITHDRAW_SOL,
  MAIN_SET_WALLET_SIZE,
  MAIN_DIVIDE_SOL,
  MAIN_GATHER_SOL,
  MAIN_REFRESH,

  HELP_BACK,
}

export enum StateCode {
  IDLE = 1000,
  WAIT_WITHDRAW_WALLET_ADDRESS,
  WAIT_SET_WALLET_SIZE,
  WAIT_SET_TOKEN_SYMBOL,
  WAIT_SET_TARGET,
  WAIT_SET_RATING,
  WAIT_SET_BUY_AMOUNT,
}

export const LOG_TAG = "================ Angel ================";
